import Link from "next/link";
import { getGame } from "@/lib/games/registry";

export default function VoidRunPage() {
  const game = getGame("void-run")!;
  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      <div className="rounded-2xl p-8 mb-6 border relative overflow-hidden"
        style={{ background: "rgba(139,92,246,0.08)", borderColor: "rgba(139,92,246,0.3)" }}>
        <div className="absolute top-0 right-0 text-[120px] opacity-10 leading-none">🌀</div>
        <div className="relative z-10">
          <div className="text-xs font-mono mb-2" style={{ color: game.color }}>VOID RUN</div>
          <h1 className="text-3xl font-bold mb-2">Enter the Void</h1>
          <p className="text-sm max-w-lg" style={{ color: "var(--text-muted)" }}>
            Rooms shift. Puzzles bend. Submit your answers and let GenLayer reason about their
            validity with nuance and creativity. No hardcoded answers — the AI judges you.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <Link href="/games/void-run/run/new"
          className="block rounded-xl p-6 border text-center transition-all hover:scale-[1.01]"
          style={{ background: "rgba(139,92,246,0.1)", borderColor: "rgba(139,92,246,0.4)" }}>
          <div className="text-3xl mb-3">🌀</div>
          <div className="font-bold mb-1">Start New Run</div>
          <div className="text-sm" style={{ color: "var(--text-muted)" }}>Enter the shifting void.</div>
        </Link>
        <Link href="/translate?target=void-run"
          className="block rounded-xl p-6 border text-center transition-all hover:scale-[1.01]"
          style={{ background: "var(--surface)", borderColor: "var(--border)" }}>
          <div className="text-3xl mb-3">💎</div>
          <div className="font-bold mb-1">Translate Relics</div>
          <div className="text-sm" style={{ color: "var(--text-muted)" }}>
            Bring items from other worlds into the void.
          </div>
        </Link>
      </div>

      <div className="rounded-xl p-6 border" style={{ background: "var(--surface)", borderColor: "var(--border)" }}>
        <h2 className="font-bold mb-3">How VoidRun Works</h2>
        <div className="space-y-3 text-sm" style={{ color: "var(--text-muted)" }}>
          <div>🚪 Each run has 5 rooms generated by GenLayer AI.</div>
          <div>🧩 Puzzle rooms ask riddles, patterns, and creative questions.</div>
          <div>⬡ GenLayer judges your answers — not a hardcoded answer key.</div>
          <div>💎 Translated relics from other games grant special abilities.</div>
          <div>🏆 Complete the run to claim a unique void reward item.</div>
        </div>
        <div className="mt-4 p-3 rounded-lg text-xs font-mono"
          style={{ background: "rgba(139,92,246,0.08)", color: "#8B5CF6" }}>
          GenLayer confidence scores range 0.0–1.0. Creative answers are rewarded.
        </div>
      </div>
    </div>
  );
}
